### ISSUE TITLE
Adjust Imports in backend

### ISSUE THREAD

**Issue by BraunRudolf** [bescka/spreadsheet_upload_tool#12]
Currently, the working directory for the backend must be ./backend-app/
we should change the imports to ./backend-app/app

**Comment by BraunRudolf** [comment]
Discuss 
https://stackoverflow.com/questions/64943693/what-are-the-best-practices-for-structuring-a-fastapi-project

Official project structure matches current one, post suggest a slightly different one.
**Question**: Keep current structure or change to new one

**Comment by bescka** [comment]
Can see the logic, app.(import) / recommended mapping seems fine.
